{% set name = "elyra-code-snippet-extension" %}
{% set version = "3.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-code-snippet-extension-{{ version }}.tar.gz
  sha256: 4ab1377d9fa2977656b064ca0e7a6d23b2db0702ce481e3a17210c1c59ad5c6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.8
  run:
    - elyra-server =={{ version }}
    - python >=3.8

test:
  commands:
    - exit 0

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra JupyterLab extension providing support for Code Snippets. Learn more at https://elyra.readthedocs.io/en/stable/user_guide/code-snippets.html
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
