{% set name = "elyra-code-snippet-extension" %}
{% set version = "3.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-code-snippet-extension-{{ version }}.tar.gz
  sha256: c4dde216e917f2d451bdee95f9dc5f36689a55ce975ac0d4c964b16b02481553

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - elyra-server ==3.6.0
    - python >=3.7

test:
  commands:
    - exit 0

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra JupyterLab extension providing support for Code Snippets. Learn more at https://elyra.readthedocs.io/en/stable/user_guide/code-snippets.html
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
